DynamicMVC/Models/ChallengeOneModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynamicMVC.Models
{
    public class ChallengeOneModel
    {
        public string Str { get; set; }
    }
}

DynamicMVC/Models/ChallengeThreeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DynamicMVC.Models
{
    public class ChallengeThreeModel
    {
        [Display(Name = "Alias")]
        public string Alias { get; set; }
        [Display(Name = "Age")]
        public int Age { get; set; }
        [Display(Name = "Favorite Color")]
        public string FavoriteColor { get; set; }

        public bool IsSubmitted { get; set; }

    }
}

DynamicMVC/Models/ChallengeTwoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynamicMVC.Models
{
    public class ChallengeTwoModel
    {
        public string Str { get; set; }
    }
}

DynamicMVC/Controllers/ChallengeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DynamicMVC.Models;
namespace DynamicMVC.Controllers
{
    public class ChallengeController : Controller
    {
        public async Task<IActionResult> One(bool id)
        {
            if (id)
            {
                Guid guid = new Guid();
                guid = Guid.NewGuid();
                ChallengeOneModel model = new ChallengeOneModel() { Str = $"This came from the server! {guid.ToString()}" };
                return View(model);
            }
            return View();
        }
        public async Task<IActionResult> Two(ChallengeTwoModel model)
        {
            if(model == null || model.Str == null)
            {
                model = new ChallengeTwoModel() { Str = "One Day, Everything Will Be Just Fine." };
            }
            return View(model);
        }
        [HttpPost]
        public JsonResult LowerCaseTransform([FromBody]string txt)
        {
            string result = txt;
            if (!String.IsNullOrEmpty(result))
            {
                result = result.ToLower();
            }
            return Json(result);
        }
        public async Task<IActionResult> Three()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Three(ChallengeThreeModel model)
        {
            model.IsSubmitted = true;
            return View(model);
        }


        public async Task<IActionResult> Four()
        {
            return View();
        }
        public async Task<IActionResult> Five()
        {
            return View();
        }
    }
}

DynamicMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DynamicMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DynamicMVC/Views/Challenge/Five.cshtml
<h2>Five</h2>

DynamicMVC/Views/Challenge/Four.cshtml
<h2>Four</h2>

DynamicMVC/Views/Challenge/One.cshtml
@model ChallengeOneModel
<h2>Challenge 1</h2>
<p>Return a String from the Server.</p>
<img alt="leaves" src="~/images/leaves.gif" id="rightImg" />
<a asp-controller="Challenge" asp-action="One" asp-route-id="True">Get String</a>

@if (Model != null && !String.IsNullOrEmpty(Model.Str))
{
    <p>@Model.Str</p>
}

DynamicMVC/Views/Challenge/Three.cshtml
@model ChallengeThreeModel
<h2>Challenge 3</h2>
<p>Basic Data Binding</p>
<img alt="leaves" src="~/images/leaves.gif" id="rightImg" />
<form asp-controller="Challenge" asp-action="Three" method="post" class="form-horizontal" role="form">
    <div class="form-group">
        <label asp-for="Alias" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Alias" class="form-control" size="30" />
            <span asp-validation-for="Alias" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="FavoriteColor" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="FavoriteColor" class="form-control" size="30" />
            <span asp-validation-for="FavoriteColor" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Age" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Age" class="form-control" size="30" />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Submit" />
        </div>
    </div>
</form>

@if(Model != null && Model.IsSubmitted)
{
    <br /><h2>Binding Results:</h2>
    <p>Alias: @Model.Alias</p>
    <p>Age: @Model.Age</p>
    <p>Favorite Color: @Model.FavoriteColor</p>
}

DynamicMVC/Views/Challenge/Two.cshtml
@model ChallengeTwoModel
@section scripts {
    <script type="text/javascript">
        var testProp = @Json.Serialize(Model.Str)
        document.getElementById("txtArea1").value = testProp;

        function ToLowerJS() {
            var str = document.getElementById("txtArea1").value;
            var result = str.toLowerCase();
            document.getElementById("txtArea1").value = result;
        }
        function ToLowerServer() {
            var str = document.getElementById("txtArea1").value;
            $.ajax({
                type: "POST",
                dataType: 'text',//'application/json; charset=utf-8',
                cache: false,
                data: JSON.stringify(str),
                url: '@Url.Action("LowerCaseTransform", "Challenge")',
                contentType: 'application/json; charset=utf-8',
                success: function (result) {
                    console.log('success');
                    console.log(result);
                    document.getElementById("txtArea1").value = stripquotes(result);
                },
                error: function (err) {
                    console.log('error');
                    console.log(err);
                },
            });
        }
        function stripquotes(a) {
            if (a.charAt(0) === '"' && a.charAt(a.length - 1) === '"') {
                return a.substr(1, a.length - 2);
            }
            return a;
        }
    </script>
}
<h2>Challenge 2</h2>
<p>Client and server-side data manipulation.</p>
<img alt="leaves" src="~/images/leaves.gif" id="rightImg" />

@Html.TextArea("txtArea1")

<br />
<a onclick="ToLowerJS()" href="#">Client-side To Lowercase!</a><br />
<a onclick="ToLowerServer()" href="#">Server-side To Lowercase!</a><br />
<a asp-controller="Challenge" asp-action="Two">Reset</a>

DynamicMVC/Views/Home/Index.cshtml
<h2>Challenge Summary</h2>
<img alt="leaves" src="~/images/leaves.gif" id="rightImg" />
<p><b>Challenge 1:</b> Return a String from the Server.</p>
<p><b>Challenge 2:</b> Client-side and Server-side data manipulation.</p>
<p><b>Challenge 3:</b> Basic Data Binding.</p>
<p><b>Challenge 4:</b> Model Validation (String Length, Email Address, Age).</p>
<p><b>Challenge 5:</b> Dynamic Collections (Add, Remove, Modify).</p>

DynamicMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dynamic MVC</title>
    <link href="~/content/initial.css" rel="stylesheet" />
    <link href="~/content/basics.css" rel="stylesheet" />
    <script src="~/js/jquery.js"></script>
</head>
<body>
    <div id="outer">
        <div id="hdr">
            <h1>Dynamic MVC by CABE</h1>
        </div>
        <div id="nav">
            <h2>Navigation</h2>
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Challenge" asp-action="One">Challenge 1</a></li>
                <li><a asp-controller="Challenge" asp-action="Two">Challenge 2</a></li>
                <li><a asp-controller="Challenge" asp-action="Three">Challenge 3</a></li>
                <li><a asp-controller="Challenge" asp-action="Four">Challenge 4</a></li>
                <li><a asp-controller="Challenge" asp-action="Five">Challenge 5</a></li>
            </ul>
        </div>
        <div id="cont">
            @RenderBody()
            @RenderSection("scripts", required: false)
        </div>
        <div id="ftr">CABE @DateTime.Now.Year</div>
    </div>
</body>
</html>